#pragma once

#include "AxeTypes.h"

static const EffectLabel __EFFECT_NAME_TABLE[] PROGMEM = {
    {"COMPRS", "CMP"},
    {"GRAFEQ", "GEQ"},
    {"PARAEQ", "PEQ"},
    {"AMP", "AMP"},
    {"CAB", "CAB"},
    {"REVERB", "REV"},
    {"DELAY-", "DLY"},
    {"MLTTAP", "MTD"},
    {"CHORUS", "CHO"},
    {"FLANGE", "FLG"},
    {"ROTARY", "ROT"},
    {"PHASER", "PHR"},
    {"WAAAAH", "WAH"},
    {"FORMNT", "FRM"},
    {"VOLUMN", "VOL"},
    {"TREMOL", "TRM"},
    {"PITCH-", "PIT"},
    {"FILTER", "FIL"},
    {"DRIVES", "DRV"},
    {"NHANCE", "ENH"},
    {"MIXERS", "MIX"},
    {"SYNTHS", "SYN"},
    {"VOCODR", "VOC"},
    {"MEGATP", "MGT"},
    {"CRSOVR", "XVR"},
    {"GATES-", "GTE"},
    {"RINGMD", "RNG"},
    {"MLTCMP", "MBC"},
    {"TENTAP", "TTD"},
    {"RESONA", "RES"},
    {"LOOPER", "LPR"},
    {"TONEMZ", "TMA"},
    {"RTAAAA", "RTA"},
    {"PLEX--", "PLX"},
    {"FBSEND", "SND"},
    {"FBRTRN", "RET"},
    {"MIDI--", "MIDI"},
    {"MLTPLX", "MUX"},
    {"IRPLYR", "IRP"},
    {"->NO!<-", "???"},
};